[package]
name = "my_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.15.0"
lalrpop = "0.22.1"
inkwell = { version = "0.5.0", features = ["llvm16-0"] }
anyhow = "1.0" # For error handling
lalrpop-util = "0.22.1"

[build-dependencies]
lalrpop = "0.22.1"  
